Add central options and testing framework
idinium96/tf2autobot pull request #161
Opened 2020-11-20 13:50 UTC by joekiller

The point of this feature is to add a useful set of tests which can be expanded upon as new features arrive. The test framework is Jest.

Add Centralize Option loading and default settings
Add Testing of option loading
Fixes #142

2020-11-20 14:01 UTC, joekiller commented
Outside of src/lib/DiscordWebhook/userSettings.ts this should be functional.

I'm thinking the options parser could use an optional warning message to print for important missing values

2020-11-20 14:03 UTC, joekiller commented
There is one linting warning I need to fix too

2020-11-20 17:08 UTC, idinium96 commented
`AutoKeys` → `Autokeys`
`CraftWeapon` → `Craftweapon`
`skipBPTFTradeOfferURL` → `skipBPTFTradeofferURL`
`discordWebhookUserName` → `discordWebhookUsername`
`invalidValueExceptionSKUs` → `invalidValueExceptionSKUS`
`customHow2TradeMessage` → `customHow2tradeMessage`

2020-11-21 05:28 UTC, joekiller commented
This is ready for review.

2020-11-21 23:28 UTC, idinium96 requested changes

2020-11-21 23:33 UTC, idinium96 commented on src/classes/Cart.ts
> +    static stringify(steamID: SteamID, disableCraftWeaponAsCurrency: boolean): string {
oh I see.. this doesn't matter.

2020-11-21 23:38 UTC, joekiller commented on src/classes/Autokeys/userSettings.ts
> +        value: !scrapAdjustmentValue ? 0 : scrapAdjustmentValue
Is that necessary?
```
> !NaN
true
> !undefined
true
> !""
true
> !null
true
```

2020-11-21 23:42 UTC, idinium96 commented on src/classes/Autokeys/userSettings.ts
> +        value: !scrapAdjustmentValue ? 0 : scrapAdjustmentValue
ah, I see. alright then. 👌

2020-11-21 23:47 UTC, joekiller commented on src/classes/Pricelist.ts
> +            if (match === null || match.autoprice || isEnableScrapAdjustmentWithAutoprice) {
seems safe in nodejs 12 but I'll include it

```
const match = null;
> if (match === null || match.autoprice || bob.uncle) { console.log("nooo"); }
nooo
undefined
>
```

2020-11-22 00:18 UTC, merged